package sv.edu.ufg.UIlogin;

import java.awt.Color;
import sv.edu.ufg.LOencrypt.cAES;
import sv.edu.ufg.LOencrypt.cArchive;
import sv.edu.ufg.LOencrypt.cLogin;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author UFG
 */
public class Encryptor extends javax.swing.JFrame {
    
    cAES objAES = new cAES();
    cArchive objArc = new cArchive();
    cLogin objLogin = new cLogin();
    

    /**
     * Creates new form Encryptor
     */
    public Encryptor() {
        initComponents();
        jParchivo.setVisible(false);
        jPtexto.setVisible(false);
        jLuser.setText(objLogin.getUsuarioAdmin());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPleft = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLuser = new javax.swing.JLabel();
        jBencrt = new javax.swing.JButton();
        jBsalir = new javax.swing.JButton();
        jBencra = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPInstruccion = new javax.swing.JPanel();
        jPtexto = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTentrada = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTsalida = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jBencriptar = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jTsecKey = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jParchivo = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLopenm = new javax.swing.JLabel();
        jBaEncrypt = new javax.swing.JButton();
        jBaDecrypt = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLmensajefinal = new javax.swing.JLabel();
        jLsalidam = new javax.swing.JLabel();
        jBopenar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTllavea = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("CODE"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1000, 690));
        setSize(new java.awt.Dimension(1000, 675));

        jPleft.setBackground(new java.awt.Color(0, 204, 0));
        jPleft.setPreferredSize(new java.awt.Dimension(350, 650));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("AESEncryptor");

        jLuser.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLuser.setForeground(new java.awt.Color(255, 255, 255));

        jBencrt.setBackground(new java.awt.Color(0, 204, 0));
        jBencrt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBencrt.setForeground(new java.awt.Color(255, 255, 255));
        jBencrt.setText("Encriptar Texto");
        jBencrt.setBorder(null);
        jBencrt.setBorderPainted(false);
        jBencrt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBencrt.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jBencrt.setFocusable(false);
        jBencrt.setHideActionText(true);
        jBencrt.setPreferredSize(new java.awt.Dimension(350, 60));
        jBencrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBencrtActionPerformed(evt);
            }
        });

        jBsalir.setBackground(new java.awt.Color(0, 204, 0));
        jBsalir.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBsalir.setForeground(new java.awt.Color(255, 255, 255));
        jBsalir.setText("Salir");
        jBsalir.setBorder(null);
        jBsalir.setBorderPainted(false);
        jBsalir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBsalir.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jBsalir.setFocusable(false);
        jBsalir.setHideActionText(true);
        jBsalir.setPreferredSize(new java.awt.Dimension(350, 60));
        jBsalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBsalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBsalirMouseExited(evt);
            }
        });
        jBsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalirActionPerformed(evt);
            }
        });

        jBencra.setBackground(new java.awt.Color(0, 204, 0));
        jBencra.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBencra.setForeground(new java.awt.Color(255, 255, 255));
        jBencra.setText("Encriptar Archivo");
        jBencra.setBorder(null);
        jBencra.setBorderPainted(false);
        jBencra.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBencra.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jBencra.setFocusable(false);
        jBencra.setHideActionText(true);
        jBencra.setPreferredSize(new java.awt.Dimension(350, 60));
        jBencra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBencraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBencraMouseExited(evt);
            }
        });
        jBencra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBencraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPleftLayout = new javax.swing.GroupLayout(jPleft);
        jPleft.setLayout(jPleftLayout);
        jPleftLayout.setHorizontalGroup(
            jPleftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPleftLayout.createSequentialGroup()
                .addGroup(jPleftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPleftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPleftLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLuser, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(48, 48, 48))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPleftLayout.createSequentialGroup()
                            .addGap(65, 65, 65)
                            .addComponent(jLabel1)))
                    .addComponent(jBencrt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBencra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBsalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPleftLayout.setVerticalGroup(
            jPleftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPleftLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 188, Short.MAX_VALUE)
                .addComponent(jLuser, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jBencrt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jBencra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jBsalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        jLayeredPane1.setPreferredSize(new java.awt.Dimension(650, 650));

        jPInstruccion.setBackground(new java.awt.Color(51, 51, 51));
        jPInstruccion.setForeground(new java.awt.Color(255, 255, 255));
        jPInstruccion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPtexto.setBackground(new java.awt.Color(51, 51, 51));
        jPtexto.setMinimumSize(new java.awt.Dimension(0, 0));
        jPtexto.setPreferredSize(new java.awt.Dimension(650, 650));
        jPtexto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTentrada.setBackground(new java.awt.Color(0, 0, 0));
        jTentrada.setColumns(20);
        jTentrada.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jTentrada.setForeground(new java.awt.Color(0, 255, 0));
        jTentrada.setRows(5);
        jTentrada.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTentrada.setMargin(new java.awt.Insets(2, 4, 2, 2));
        jScrollPane2.setViewportView(jTentrada);

        jPtexto.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 510, 180));

        jTsalida.setBackground(new java.awt.Color(0, 0, 0));
        jTsalida.setColumns(20);
        jTsalida.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jTsalida.setForeground(new java.awt.Color(0, 204, 0));
        jTsalida.setRows(5);
        jScrollPane3.setViewportView(jTsalida);

        jPtexto.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 510, 190));

        jLabel3.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ingrese Texto");
        jPtexto.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        jBencriptar.setBackground(new java.awt.Color(0, 0, 0));
        jBencriptar.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jBencriptar.setForeground(new java.awt.Color(255, 255, 255));
        jBencriptar.setText("Encriptar");
        jBencriptar.setPreferredSize(new java.awt.Dimension(125, 40));
        jBencriptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBencriptarActionPerformed(evt);
            }
        });
        jPtexto.add(jBencriptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, -1, -1));

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Desencriptar");
        jButton4.setPreferredSize(new java.awt.Dimension(125, 40));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPtexto.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 160, -1));

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Clear");
        jButton6.setPreferredSize(new java.awt.Dimension(125, 40));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPtexto.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, -1, -1));

        jTsecKey.setBackground(new java.awt.Color(0, 0, 0));
        jTsecKey.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jTsecKey.setForeground(new java.awt.Color(0, 204, 0));
        jPtexto.add(jTsecKey, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 190, -1));

        jLabel4.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ingrese Key");
        jPtexto.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, -1, -1));
        jPtexto.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Fondo2.png"))); // NOI18N
        jPtexto.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jParchivo.setBackground(new java.awt.Color(51, 51, 51));
        jParchivo.setToolTipText("");
        jParchivo.setPreferredSize(new java.awt.Dimension(650, 650));
        jParchivo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Seleccionar Archivo");
        jParchivo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, -1));

        jLopenm.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLopenm.setForeground(new java.awt.Color(102, 102, 255));
        jParchivo.add(jLopenm, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 280, 30));

        jBaEncrypt.setBackground(new java.awt.Color(0, 0, 0));
        jBaEncrypt.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jBaEncrypt.setForeground(new java.awt.Color(255, 255, 255));
        jBaEncrypt.setText("Encriptar");
        jBaEncrypt.setPreferredSize(new java.awt.Dimension(125, 40));
        jBaEncrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBaEncryptActionPerformed(evt);
            }
        });
        jParchivo.add(jBaEncrypt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, -1));

        jBaDecrypt.setBackground(new java.awt.Color(0, 0, 0));
        jBaDecrypt.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jBaDecrypt.setForeground(new java.awt.Color(255, 255, 255));
        jBaDecrypt.setText("Desencriptar");
        jBaDecrypt.setPreferredSize(new java.awt.Dimension(125, 40));
        jBaDecrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBaDecryptActionPerformed(evt);
            }
        });
        jParchivo.add(jBaDecrypt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 160, -1));

        jButton9.setBackground(new java.awt.Color(0, 0, 0));
        jButton9.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Clear");
        jButton9.setPreferredSize(new java.awt.Dimension(125, 40));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jParchivo.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, -1, -1));
        jParchivo.add(jLmensajefinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, 220, 30));

        jLsalidam.setForeground(new java.awt.Color(102, 255, 102));
        jParchivo.add(jLsalidam, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 540, 250, 30));

        jBopenar.setBackground(new java.awt.Color(0, 0, 0));
        jBopenar.setFont(new java.awt.Font("Consolas", 0, 32)); // NOI18N
        jBopenar.setForeground(new java.awt.Color(255, 255, 255));
        jBopenar.setText("OPEN");
        jBopenar.setPreferredSize(new java.awt.Dimension(200, 50));
        jBopenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBopenarActionPerformed(evt);
            }
        });
        jParchivo.add(jBopenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, -1, -1));

        jLabel6.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ingrese llave");
        jParchivo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, -1, -1));

        jTllavea.setBackground(new java.awt.Color(0, 0, 0));
        jTllavea.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jTllavea.setForeground(new java.awt.Color(0, 204, 0));
        jParchivo.add(jTllavea, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 220, -1));
        jParchivo.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Fondo2.png"))); // NOI18N
        jParchivo.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLayeredPane1.setLayer(jPInstruccion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jPtexto, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jParchivo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPInstruccion, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPtexto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jParchivo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPInstruccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPtexto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jParchivo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPleft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPleft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void jBencraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBencraActionPerformed
        jParchivo.setVisible(true);
        jPtexto.setVisible(false);
        jPInstruccion.setVisible(false);
    }//GEN-LAST:event_jBencraActionPerformed

    private void jBencraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBencraMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jBencraMouseExited

    private void jBencraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBencraMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jBencraMouseEntered

    private void jBsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalirActionPerformed
        new UILogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBsalirActionPerformed

    private void jBsalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBsalirMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jBsalirMouseExited

    private void jBsalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBsalirMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jBsalirMouseEntered

    private void jBencrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBencrtActionPerformed
        jPtexto.setVisible(true);
        jParchivo.setVisible(false);
        jPInstruccion.setVisible(false);
    }//GEN-LAST:event_jBencrtActionPerformed

    private void jBencriptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBencriptarActionPerformed
        objAES.encrypt(jTentrada.getText(), jTsecKey.getText());
        jTsalida.setText(objAES.getTextEncr());
    }//GEN-LAST:event_jBencriptarActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        objAES.decrypt(jTentrada.getText(), jTsecKey.getText());
        jTsalida.setText(objAES.getTextDecr());
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jTentrada.setText("");
        jTsalida.setText("");
        jTsecKey.setText("");
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jBaEncryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBaEncryptActionPerformed
        objAES.encrypt(objArc.getRdFile(), jTllavea.getText());
        objArc.setMfFile(objAES.getTextEncr());//Encriptacion en la variable MfFile.
        objArc.SaveFile();
        objArc.WriteFile();
        jLsalidam.setText("Ruta de Salida: "+objArc.getSvFile());
        jLmensajefinal.setText("Encriptado Exitoso!!");
    }//GEN-LAST:event_jBaEncryptActionPerformed

    private void jBopenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBopenarActionPerformed
        objArc.OpenArchive();
        jLopenm.setText("Ruta de entrada: "+objArc.getOpFile());
        objArc.ReadFile();
    }//GEN-LAST:event_jBopenarActionPerformed

    private void jBaDecryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBaDecryptActionPerformed
        objAES.decrypt(objArc.getRdFile(), jTllavea.getText());   
        objArc.setMfFile(objAES.getTextDecr());
        objArc.SaveFile();
        objArc.WriteFile();
        jLsalidam.setText("Ruta de Salida: "+objArc.getSvFile());
        jLmensajefinal.setText("Decriptado Exitoso!!");
    }//GEN-LAST:event_jBaDecryptActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        jLsalidam.setText("");
        jLopenm.setText("");
        objArc.setMfFile("");
        objArc.setOpFile("");
        objArc.setRdFile("");
        objArc.setSvFile("");
        jTllavea.setText("");
        jLmensajefinal.setText("");
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Encryptor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Encryptor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Encryptor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Encryptor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Encryptor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBaDecrypt;
    private javax.swing.JButton jBaEncrypt;
    private javax.swing.JButton jBencra;
    private javax.swing.JButton jBencriptar;
    private javax.swing.JButton jBencrt;
    private javax.swing.JButton jBopenar;
    private javax.swing.JButton jBsalir;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel jLmensajefinal;
    private javax.swing.JLabel jLopenm;
    private javax.swing.JLabel jLsalidam;
    private javax.swing.JLabel jLuser;
    private javax.swing.JPanel jPInstruccion;
    private javax.swing.JPanel jParchivo;
    private javax.swing.JPanel jPleft;
    private javax.swing.JPanel jPtexto;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTentrada;
    private javax.swing.JTextField jTllavea;
    private javax.swing.JTextArea jTsalida;
    private javax.swing.JTextField jTsecKey;
    // End of variables declaration//GEN-END:variables
}
